# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import interface_pb2 as interface__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoseServiceStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCoordinates = channel.unary_unary(
                '/PoseService.PoseService/SendCoordinates',
                request_serializer=interface__pb2.CoordinatesRequest.SerializeToString,
                response_deserializer=interface__pb2.CoordinatesResponse.FromString,
                _registered_method=True)


class PoseServiceServicer(object):
    """Define the gRPC service
    """

    def SendCoordinates(self, request, context):
        """RPC method for sending coordinates and receiving a response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCoordinates': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCoordinates,
                    request_deserializer=interface__pb2.CoordinatesRequest.FromString,
                    response_serializer=interface__pb2.CoordinatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PoseService.PoseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PoseService.PoseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoseService(object):
    """Define the gRPC service
    """

    @staticmethod
    def SendCoordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PoseService.PoseService/SendCoordinates',
            interface__pb2.CoordinatesRequest.SerializeToString,
            interface__pb2.CoordinatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
