# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interface.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\x12\x0bPoseService\"\x9e\x01\n\x12\x43oordinatesRequest\x12\x12\n\nposition_x\x18\x01 \x01(\x02\x12\x12\n\nposition_y\x18\x02 \x01(\x02\x12\x12\n\nposition_z\x18\x03 \x01(\x02\x12\x18\n\x10orientation_roll\x18\x04 \x01(\x02\x12\x19\n\x11orientation_pitch\x18\x05 \x01(\x02\x12\x17\n\x0forientation_yaw\x18\x06 \x01(\x02\"&\n\x13\x43oordinatesResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2c\n\x0bPoseService\x12T\n\x0fSendCoordinates\x12\x1f.PoseService.CoordinatesRequest\x1a .PoseService.CoordinatesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDINATESREQUEST']._serialized_start=33
  _globals['_COORDINATESREQUEST']._serialized_end=191
  _globals['_COORDINATESRESPONSE']._serialized_start=193
  _globals['_COORDINATESRESPONSE']._serialized_end=231
  _globals['_POSESERVICE']._serialized_start=233
  _globals['_POSESERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
